In [1]:
import keras
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as tts 

Using TensorFlow backend.


In [2]:
train=pd.read_csv('D:\\Kaggle\\Digit Recognizer\\train.csv')
test=pd.read_csv('D:\\Kaggle\\Digit Recognizer\\test.csv')

In [3]:
train.shape,test.shape

((42000, 785), (28000, 784))

In [4]:
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [5]:
test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [6]:
train['label']

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [7]:
X_train=train.drop(labels=['label'],axis=1)
X_train.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [8]:
y_train=train['label']
y_train.head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [9]:
X_train=X_train.astype('float32')
test=test.astype('float32')
X_train=X_train/255
test=test/255

In [10]:
y_train = keras.utils.to_categorical(y_train, 10)
y_train.shape

(42000, 10)

In [11]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [12]:
X_train,X_train.shape

(       pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
 0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 ...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
 41995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 41996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 41997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 41998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 41999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 
        pixel9

In [13]:
X_train=X_train.values.reshape(-1,28,28,1)
test=test.values.reshape(-1,28,28,1)

In [14]:
X_train.shape

(42000, 28, 28, 1)

In [15]:
X_train,X_test,y_train,y_test= tts(X_train,y_train,test_size=0.2,random_state=42)

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense,Dropout

In [17]:
cf=Sequential()

In [18]:
cf.add(Conv2D(32,(3,3),padding='same',input_shape=(28,28,1),activation='relu'))
cf.add(Conv2D(32,(3,3),activation='relu'))
cf.add(MaxPooling2D(pool_size=(2,2)))
cf.add(Dropout(0.25))

In [19]:
cf.add(Conv2D(32,(3,3),padding='same',input_shape=(28,28,1),activation='relu'))
cf.add(Conv2D(32,(3,3),activation='relu'))
cf.add(MaxPooling2D(pool_size=(2,2)))
cf.add(Dropout(0.25))

In [20]:
cf.add(Flatten())
cf.add(Dense(512,activation='relu'))
cf.add(Dropout(0.5))
cf.add(Dense(10,activation='softmax'))

In [21]:
cf.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [22]:
cf.fit(X_train,y_train,batch_size=32,epochs=30,validation_data=(X_test,y_test),shuffle=True)

Epoch 1/30
1050/1050 [==============================] - 18s 17ms/step - loss: 0.2314 - accuracy: 0.9251 - val_loss: 0.0537 - val_accuracy: 0.9833
Epoch 2/30
1050/1050 [==============================] - 17s 16ms/step - loss: 0.0772 - accuracy: 0.9759 - val_loss: 0.0377 - val_accuracy: 0.9883
Epoch 3/30
1050/1050 [==============================] - 17s 17ms/step - loss: 0.0612 - accuracy: 0.9815 - val_loss: 0.0393 - val_accuracy: 0.9874
Epoch 4/30
1050/1050 [==============================] - 16s 15ms/step - loss: 0.0497 - accuracy: 0.9850 - val_loss: 0.0282 - val_accuracy: 0.9902
Epoch 5/30
1050/1050 [==============================] - 14s 13ms/step - loss: 0.0456 - accuracy: 0.9856 - val_loss: 0.0300 - val_accuracy: 0.9902
Epoch 6/30
1050/1050 [==============================] - 14s 13ms/step - loss: 0.0393 - accuracy: 0.9877 - val_loss: 0.0309 - val_accuracy: 0.9896
Epoch 7/30
1050/1050 [==============================] - 15s 14ms/step - loss: 0.0365 - accuracy: 0.9892 - val_loss: 0.0394 -

In [23]:
# results=cf.predict(test)

In [24]:
test[0]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [25]:
# results = np.argmax(results,axis = 1)
# results = pd.Series(results,name="Label")

In [26]:
# submission = pd.concat([pd.Series(range(1,28001),name = "ImageId"),results],axis = 1)

# submission.to_csv("submission.csv",index=False)

In [69]:
from tensorflow.keras.preprocessing.image import load_img,img_to_array
import matplotlib.pyplot as plt
img=load_img('....\\Kaggle\\Digit Recognizer\\Image\\image.jpg')
print(type(img))
print(img.format)
print(img.mode)
print(img.size)
img.show()

<class 'PIL.JpegImagePlugin.JpegImageFile'>
JPEG
RGB
(1274, 1280)


In [70]:
img_array = img_to_array(img)
print(img_array.dtype)
print(img_array.shape)

float32
(1280, 1274, 3)


In [71]:
img = img.resize((28,28))
img

In [72]:
img=np.invert(img.convert('L')).ravel()

In [73]:
#  img = np.invert(img)

In [74]:
img = img.reshape(1,28,28,1)

In [75]:
img = img/255.0
img

array([[[[0.00392157],
         [0.00392157],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.00392157],
         [0.00784314],
         [0.02352941],
         [0.05490196],
         [0.10196078]],

        [[0.00392157],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         [0.        ],
         

In [76]:
result=cf.predict([img])
result

array([[1.2303629e-16, 2.1027263e-11, 1.0000000e+00, 3.8600221e-09,
        1.1068780e-15, 1.1638519e-19, 4.0275295e-17, 1.4364820e-09,
        6.5844556e-16, 8.6811269e-16]], dtype=float32)

In [77]:
import tensorflow as tf
res=np.argmax(result,axis=1)
res[0]

2